[project]
name = "persiapress-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain-core>=0.3.58",
    "langchain-openai>=0.3.16",
    "markdown>=3.8",
    "streamlit>=1.45.0",
]
